 - apt: update_cache=yes
 - apt: name=nginx state=present

 - file: path=/etc/nginx/sites-enabled/default state=absent
 - template: src=alum dest=/etc/nginx/sites-available/alum
 - file: path=/etc/nginx/sites-enabled/alum src=../sites-available/alum state=link

 - command: openssl dhparam -out /etc/nginx/dhparam.pem 2048 creates=/etc/nginx/dhparam.pem
 - copy: src={{ domain }}.pem dest=/etc/nginx/{{ domain }}.pem mode=600
 - copy: src={{ mirror }}.pem dest=/etc/nginx/{{ mirror }}.pem mode=600

 - service: name=nginx state=restarted


 - apt: pkg=daemontools
 - apt: pkg=daemontools-run

 - file: path=/root/alum/log/main/ state=directory
 - copy: src=run.sh dest=/root/alum/run mode=0755
 - copy: src=log.sh dest=/root/alum/log/run mode=0755

 - file: path=/root/www_alum/ state=directory
 - copy: src=www_alum/www_alum dest=/root/www_alum/www_alum mode=0755
 - copy: src=www_alum/form.html dest=/root/www_alum/form.html
 - copy: src=www_alum/error.html dest=/root/www_alum/error.html
 - copy: src=www_alum/config.yml dest=/root/www_alum/config.yml

 - file: path=/etc/service/alum state=link src=/root/alum

 - service: name=svscan state=started
 - command: svc -u /etc/service/alum/
 - command: svc -i /etc/service/alum/
